---
- name: setting up local gen
  copy: 
    src: "locale.gen"
    dest: "/etc/locale.gen"
    force: yes
    
- name: local gen command
  shell:
    cmd: locale-gen

- name: setting timezone
  shell:
    cmd: timedatectl set-timezone "{{ timezone }}"
